spring.application.name=BLOB
server.port=${PORT:8080}
spring.main.allow-bean-definition-overriding=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# ========================================================
# CORE DATABASE STORAGE (POSTGRESQL) - DYNAMIC VARIABLES
# ========================================================
spring.jpa.show-sql=true

# ========================================================
# SERVICE REGISTRY DISABLED
# ========================================================
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


# ========================================================
# DATABASE CONFIGURATION
# ========================================================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ========================================================
# REDIS CONFIGURATION (SPRING BOOT 3.x)
# ========================================================
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:${SPRING_REDIS_HOST:nozomi.proxy.rlwy.net}}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:${SPRING_REDIS_PORT:44303}}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:${SPRING_REDIS_PASSWORD:}}
spring.data.redis.timeout=6000ms