spring.application.name=BLOB
server.port=${PORT}
spring.main.allow-bean-definition-overriding=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# ? ENSURES BLOB_DB TABLES ARE AUTO-CREATED
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true

# ? PREVENTS SPRING FROM ATTEMPTING TO USE LOCAL CACHE MANAGERS
spring.cache.type=none

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.password=${SPRING_REDIS_PASSWORD}
spring.data.redis.timeout=6000ms

server.compression.enabled=true
server.compression.mime-types=application/json,text/html,text/xml,text/plain
server.compression.min-response-size=1024
