# Give it a unique name (This MUST match what you put in the Gateway YAML)
spring.application.name=BLOB
server.port=8095

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Make instances send a heartbeat every 5 seconds for rapid discovery
eureka.instance.lease-renewal-interval-in-seconds=5
# Allow 15 seconds before the registry expires an instance
eureka.instance.lease-expiration-duration-in-seconds=15